#!/bin/bash

# Script to generate Mender integration binaries for Raspberry Pi boards
#
# Files that will be packaged:
#
#     - u-boot.bin
#     - fw_printenv
#     - fw_env.config
#     - boot.scr
#
# NOTE! This script is not necessarily well tested and the main purpose
# is to provide an reference on how the current integration binaries where
# generated.

set -e

export CROSS_COMPILE=arm-linux-gnueabihf-
export ARCH=arm

# Test if the toolchain is actually installed
arm-linux-gnueabihf-gcc --version

UBOOT_MENDER_BRANCH=2018.07
git clone https://github.com/mendersoftware/uboot-mender.git -b mender-rpi-${UBOOT_MENDER_BRANCH}
cd uboot-mender

# Change defconfig depending which RPi you are targeting e.g
# raspberrypi0w_defconfig for RPi Zero WiFi.
make rpi_3_32b_defconfig
make
make envtools

# This script is copied from an stock Armbian image and has been modified
# slightly to work with Mender.
cat <<- 'EOF' > boot.cmd
# DO NOT EDIT THIS FILE
#

fdt addr ${fdt_addr} && fdt get value bootargs /chosen bootargs
run mender_setup
mmc dev ${mender_uboot_dev}
load ${mender_uboot_root} ${kernel_addr_r} /boot/zImage
bootz ${kernel_addr_r} - ${fdt_addr}
run mender_try_to_recover

# Recompile with:
# mkimage -C none -A arm -T script -d boot.cmd boot.scr
EOF

mkimage -C none -A arm -T script -d boot.cmd boot.scr

cat <<- EOF > fw_env.config
/dev/mmcblk0 0x400000 0x4000
/dev/mmcblk0 0x800000 0x4000
EOF

mkdir integration-binaries
cp u-boot.bin tools/env/fw_printenv fw_env.config boot.scr integration-binaries/
git log --graph --pretty=oneline -15 > integration-binaries/uboot-git-log.txt
cd integration-binaries

# Change name here depending on which board you are targeting
tar cvf raspberrypi3-integration-${UBOOT_MENDER_BRANCH}.tar.gz ./*
cd -

# Writing the image to SD/eMMC
#dd if=$1/rksd_loader.img of=$2 seek=64 conv=notrunc status=none >/dev/null 2>&
