#!/bin/bash

set -e

UBOOT_MENDER_BRANCH_BBB=$(grep ^UBOOT_MENDER_BRANCH= ./build-uboot-bbb.sh | cut -d= -f2)
UBOOT_MENDER_BRANCH_RPI=$(grep ^UBOOT_MENDER_BRANCH= ./build-uboot-rpi.sh | cut -d= -f2)

mkdir -p output/upload/uboot/beaglebone
ln -f output/beaglebone_black_debian_emmc-${UBOOT_MENDER_BRANCH_BBB}.tar.gz output/upload/uboot/beaglebone/beaglebone_black_debian_emmc-${UBOOT_MENDER_BRANCH_BBB}.tar.gz
ln -f output/beaglebone_black_debian_sdcard-${UBOOT_MENDER_BRANCH_BBB}.tar.gz output/upload/uboot/beaglebone/beaglebone_black_debian_sdcard-${UBOOT_MENDER_BRANCH_BBB}.tar.gz

mkdir -p output/upload/uboot/raspberrypi
ln -f output/raspberrypi0w-${UBOOT_MENDER_BRANCH_RPI}.tar.gz output/upload/uboot/raspberrypi/raspberrypi0w-${UBOOT_MENDER_BRANCH_RPI}.tar.gz
ln -f output/raspberrypi3-${UBOOT_MENDER_BRANCH_RPI}.tar.gz output/upload/uboot/raspberrypi/raspberrypi3-${UBOOT_MENDER_BRANCH_RPI}.tar.gz
ln -f output/raspberrypi4-${UBOOT_MENDER_BRANCH_RPI}.tar.gz output/upload/uboot/raspberrypi/raspberrypi4-${UBOOT_MENDER_BRANCH_RPI}.tar.gz
